# Generated by Django 5.0 on 2025-11-28 03:58

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'marcas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve', models.CharField(choices=[('administrador', 'Administrador'), ('agente', 'Agente'), ('taller', 'Taller'), ('cliente', 'Cliente')], max_length=20, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de Usuario',
                'verbose_name_plural': 'Tipos de Usuarios',
                'db_table': 'tipos_usuarios',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('cve', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('id_tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='core.tipousuario', verbose_name='Tipo de Usuario')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('solicitud', 'Solicitud'), ('reservacion', 'Reservación'), ('servicio', 'Servicio')], max_length=50)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'estados',
                'unique_together': {('clave', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('atendible', models.BooleanField(default=True, help_text='Define si el modelo puede ser atendido')),
                ('ano_inicio', models.IntegerField(blank=True, help_text='Año desde el cual se atiende', null=True)),
                ('ano_fin', models.IntegerField(blank=True, help_text='Año hasta el cual se atiende', null=True)),
                ('activo', models.BooleanField(default=True)),
                ('id_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='core.marca')),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
                'db_table': 'modelos',
                'ordering': ['id_marca__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TampBlockPrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('disponible', models.BooleanField(default=True)),
                ('capacidad', models.IntegerField(default=1, help_text='Cuántos vehículos puede atender', validators=[django.core.validators.MinValueValidator(1)])),
                ('reservados', models.IntegerField(default=0)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Calendario Taller Principal',
                'verbose_name_plural': 'Calendarios Taller Principal',
                'db_table': 'tamp_block_principal',
                'ordering': ['fecha', 'hora_inicio'],
                'unique_together': {('fecha', 'hora_inicio')},
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=50, unique=True)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('vin', models.CharField(blank=True, help_text='Número de identificación vehicular', max_length=100, null=True, unique=True)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('id_modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='core.modelo')),
                ('id_usuario_propietario', models.ForeignKey(help_text='Cliente propietario del vehículo', on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'db_table': 'vehiculos',
                'ordering': ['-creado_at'],
            },
        ),
        migrations.CreateModel(
            name='TampBlockTalleres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('disponible', models.BooleanField(default=True)),
                ('capacidad', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('reservados', models.IntegerField(default=0)),
                ('notas', models.TextField(blank=True, null=True)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('id_usuario_taller', models.ForeignKey(help_text='Taller secundario', on_delete=django.db.models.deletion.CASCADE, related_name='calendario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calendario Taller Secundario',
                'verbose_name_plural': 'Calendarios Talleres Secundarios',
                'db_table': 'tamp_block_talleres',
                'ordering': ['fecha'],
                'unique_together': {('id_usuario_taller', 'fecha')},
            },
        ),
    ]
