# Generated by Django 5.0 on 2025-11-28 03:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('solicitudes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Pintura, Mecánica, Eléctrico, etc.', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría de Servicio',
                'verbose_name_plural': 'Categorías de Servicios',
                'db_table': 'categorias_servicios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ReservacionServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_dias', models.IntegerField(blank=True, help_text='Días reales que tardó (actualizado por taller)', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('progreso', models.IntegerField(default=0, help_text='Porcentaje 0-100%', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio_real', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin_estimada', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin_real', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservaciones_servicios', to='core.estado')),
                ('id_reservacion_taller_principal', models.ForeignKey(help_text='Reservación principal', on_delete=django.db.models.deletion.CASCADE, related_name='servicios_asignados', to='solicitudes.reservaciontallerprincipal')),
            ],
            options={
                'verbose_name': 'Reservación de Servicio',
                'verbose_name_plural': 'Reservaciones de Servicios',
                'db_table': 'reservaciones_servicios',
                'ordering': ['-fecha_asignacion'],
            },
        ),
        migrations.CreateModel(
            name='ProgresoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('porcentaje_anterior', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('porcentaje_nuevo', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('dias_estimados', models.IntegerField(blank=True, help_text='Actualización de días estimados', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('comentario', models.TextField(blank=True, null=True)),
                ('evidencia_url', models.CharField(blank=True, max_length=300, null=True)),
                ('actualizado_por', models.ForeignKey(help_text='Usuario taller que actualizó', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actualizaciones_progreso', to=settings.AUTH_USER_MODEL)),
                ('id_reservacion_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_progreso', to='servicios.reservacionservicio')),
            ],
            options={
                'verbose_name': 'Progreso de Servicio',
                'verbose_name_plural': 'Progresos de Servicios',
                'db_table': 'progreso_servicio',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ReservacionTampBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignada', models.DateField()),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('id_reservacion_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechas_calendario', to='servicios.reservacionservicio')),
                ('id_tamp_block_taller', models.ForeignKey(help_text='Fecha en calendario del taller', on_delete=django.db.models.deletion.PROTECT, related_name='reservaciones', to='core.tampblocktalleres')),
            ],
            options={
                'verbose_name': 'Reservación Calendario',
                'verbose_name_plural': 'Reservaciones Calendario',
                'db_table': 'reservaciones_tamp_block',
                'ordering': ['fecha_asignada'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('costo_base', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('duracion_estimada_dias', models.IntegerField(blank=True, help_text='Días estimados para completar', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('activo', models.BooleanField(default=True)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='servicios.categoriaservicio')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'servicios',
                'ordering': ['id_categoria__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ServicioUsuarioTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, help_text='Precio que cobra este taller', max_digits=12, null=True)),
                ('duracion_dias', models.IntegerField(blank=True, help_text='Días que tarda este taller específico', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('activo', models.BooleanField(default=True)),
                ('id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talleres_ofrecen', to='servicios.servicio')),
                ('id_usuario_taller', models.ForeignKey(help_text='Taller que ofrece el servicio', on_delete=django.db.models.deletion.CASCADE, related_name='servicios_ofrecidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Servicio de Taller',
                'verbose_name_plural': 'Servicios de Talleres',
                'db_table': 'servicio_usuario_taller',
                'unique_together': {('id_usuario_taller', 'id_servicio')},
            },
        ),
        migrations.AddField(
            model_name='reservacionservicio',
            name='id_servicio_usuario_taller',
            field=models.ForeignKey(help_text='Servicio y taller asignado', on_delete=django.db.models.deletion.PROTECT, related_name='reservaciones', to='servicios.serviciousuariotaller'),
        ),
    ]
