# Generated by Django 5.0 on 2025-11-28 03:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('motivo_rechazo', models.TextField(blank=True, help_text='Si es rechazada, aquí va el motivo', null=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, help_text='Fecha de aprobación o rechazo', null=True)),
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True)),
                ('aprobado_por', models.ForeignKey(blank=True, help_text='Administrador/agente que aprobó', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='core.estado')),
                ('id_usuario', models.ForeignKey(help_text='Cliente que solicita', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_creadas', to=settings.AUTH_USER_MODEL)),
                ('id_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='core.vehiculo')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'db_table': 'solicitudes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ReservacionTallerPrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evaluacion', models.DateTimeField(blank=True, null=True)),
                ('notas_evaluacion', models.TextField(blank=True, null=True)),
                ('avance_global', models.IntegerField(default=0, help_text='Progreso total 0-100%', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('estado_global', models.CharField(default='pendiente', max_length=100)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin_estimada', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin_real', models.DateTimeField(blank=True, null=True)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('atendido_por', models.ForeignKey(blank=True, help_text='Agente que realizó la evaluación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservaciones_principal', to='core.estado')),
                ('id_tamp_block', models.ForeignKey(help_text='Fecha/hora agendada', on_delete=django.db.models.deletion.PROTECT, related_name='reservaciones', to='core.tampblockprincipal')),
                ('id_solicitud', models.OneToOneField(help_text='Una solicitud = una reservación', on_delete=django.db.models.deletion.CASCADE, related_name='reservacion', to='solicitudes.solicitud')),
            ],
            options={
                'verbose_name': 'Reservación Taller Principal',
                'verbose_name_plural': 'Reservaciones Taller Principal',
                'db_table': 'reservaciones_taller_principal',
                'ordering': ['-creado_at'],
            },
        ),
        migrations.CreateModel(
            name='DetalleSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('costo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('id_solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='solicitudes.solicitud')),
            ],
            options={
                'verbose_name': 'Detalle de Solicitud',
                'verbose_name_plural': 'Detalles de Solicitudes',
                'db_table': 'detalle_solicitud',
            },
        ),
    ]
